server:
  port: 8008
  servlet:
    context-path: /codex/api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/codex-db
    username: alesander
    password: CodexChallenge
    hikari:
      idleTimeout: 15000
      maximumPoolSize: 20
      maxLifetime: 600000
      minimumIdle: 2
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
      generate-ddl: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    check-location: false
    locations: [ 'classpath:db/migration' ]

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true